### ISSUE TITLE
Horror police clothing

### ISSUE THREAD

**Issue by hotatchanh** [qbcore-framework/qb-clothing#28] opened 2021-09-25 08:48 UTC
![image](https://user-images.githubusercontent.com/18389268/134765499-a4718d86-2a6b-45c4-a715-fae5570e4c48.png)
This is how police look like if use default cloth config.

**Comment by Synthethics** [comment] 2021-10-15 13:48
The issue is valid, the clothes aren't fitting the police job. I'll do a PR shortly to give these a bit more of a "lore friendly" standard configuration.

**Comment by Synthethics** [comment] 2021-10-17 10:11
https://github.com/qbcore-framework/qb-clothing/pull/38 - Fixed in PR.

**Closed** 2021-10-17 15:35 UTC
